/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package truck_master_mis;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @Ioan Sorin Muntean
 */
public class principal_Vista extends javax.swing.JFrame {

    /**
     * Creado nuevo frame principal 
     */
    public principal_Vista() {
        initComponents();
        
        
        manejaComponetes mComponentes = new manejaComponetes();
        manejadorDeVentana manejaVentanas = new manejadorDeVentana();
         
         this.addComponentListener(mComponentes);
         this.addWindowListener(manejaVentanas);
          manejaClick mc = new manejaClick();
           btnHola.addActionListener(mc);
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHola.setText("HOLA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnHola)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnHola)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHola;
    // End of variables declaration//GEN-END:variables

}
class manejaClick implements ActionListener{

    @Override
    public void actionPerformed(ActionEvent e) {
        
        System.out.println(e.getActionCommand());
        System.out.println("Se ha pulsado el buton");
    }
   
    
    
}
class manejaComponetes implements ComponentListener{

        @Override
        public void componentResized(ComponentEvent e) {
            System.out.println("La ventana cambio de tamaño");
        }

        @Override
        public void componentMoved(ComponentEvent e) {
            System.out.println("La ventana se movio de sitio");
        }

        @Override
        public void componentShown(ComponentEvent e) {
            System.out.println("La controles aparecen");
        }

        @Override
        public void componentHidden(ComponentEvent e) {
            System.out.println("Los controles se ocultan");
        }
        
    }
 class manejadorDeVentana implements WindowListener{

        @Override
        public void windowOpened(WindowEvent e) {
            System.out.println(e.getNewState());
            System.out.println("Ventana abierta");
        }

        @Override
        public void windowClosing(WindowEvent e) {
            System.out.println(e.getNewState());
            System.out.println("Ventana cerrandose");
        }

        @Override
        public void windowClosed(WindowEvent e) {
            System.out.println(e.getNewState());
            System.out.println("Ventana cerrada");
        }

        @Override
        public void windowIconified(WindowEvent e) {
            System.out.println(e.getNewState());
        }

        @Override
        public void windowDeiconified(WindowEvent e) {
            System.out.println(e.getNewState());
        }

        @Override
        public void windowActivated(WindowEvent e) {
            System.out.println(e.getNewState());
        }

        @Override
        public void windowDeactivated(WindowEvent e) {
            System.out.println(e.getNewState());
        }
        
    }
